### ISSUE TITLE
Compatibility with newer .NET Framework

### ISSUE THREAD

**Issue by Nekromancer** [contre/Windows-API-Code-Pack-1.1#15]
Hi, 
I cannot install this on application targeting .NET Framework v4.6.1. Is there any option to make this work?

Error:
```
Could not install package 'Microsoft-WindowsAPICodePack-Core 1.1.3.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by contre** [comment]
I'll work on getting this working with older .net framework versions.

**Comment by contre** [comment]
Go for it.

sorry for the late reply.

**Comment by contre** [comment]
Go for it.

sorry for the late reply.

**Comment by contre** [comment]
Closing for now as I intend to move forward with framework versions and not backward
