### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by ArielKo1248** [contre/Windows-API-Code-Pack-1.1#29]
https://github.com/contre/Windows-API-Code-Pack-1.1/blob/6f3d31dd9128da67497dd3b1394fcd7c9d9a6673/source/WindowsAPICodePack/Shell/CommonFileDialogs/CommonFileDialogFilter.cs#L128

You can use instead:         rawExtension.TrimStart('.')

:)

**Comment by contre** [comment]
Put in a PR and I'll review.

**Comment by i2van** [comment]
There is a [PR](https://github.com/contre/Windows-API-Code-Pack-1.1/pull/49) for it.
