### ISSUE TITLE
Deleting files to the recycle bin.

### ISSUE THREAD

**Issue by vpenades** [contre/Windows-API-Code-Pack-1.1#31]
Hi.

I was wondering, is there any funcionality in API code pack to delete a file by sending it to the recycle bin?

Files deleted with System.IO.File.Delete are usually deleted permanently,  and I've found that sending files to the bin is surprisingly non trivial.

I already found a few solutions, but I would preffer to use something already in built in another library, specially if it's related to shell operations.

**Comment by contre** [comment]
As far as I'm aware, this functionality does not exist within these libraries. The only one that I found was to use the VB based functionality for this which can be called from C#.
