### ISSUE TITLE
Dont use MD-5 in ShellObject GetHash implementation

### ISSUE THREAD

**Issue by DanFTRX** [contre/Windows-API-Code-Pack-1.1#32]
See original ticket:   https://github.com/aybe/Windows-API-Code-Pack-1.1/issues/56

Because it is only used in the GetHashCode, it should be safe to change to something else.

**Comment by DanFTRX** [comment]
@contre If I write a Pull Request is this repo still active/taking submissions?

**Comment by contre** [comment]
Yup. Go for it.
