### ISSUE TITLE
ERROR using Microsoft.WindowsAPICodePack.Shell; -->  Missing using directive

### ISSUE THREAD

**Issue by GH-Djeff** [contre/Windows-API-Code-Pack-1.1#36]
Hello,
i try to run the following Powershell Script 
###########################################
_**using Microsoft.WindowsAPICodePack.Shell;
using Microsoft.WindowsAPICodePack.Shell.PropertySystem;

string filePath = @"D:\temp\example.docx";
var file = ShellFile.FromFilePath(filePath);

// Read and Write:

string[] oldAuthors = file.Properties.System.Author.Value;
string oldTitle = file.Properties.System.Title.Value;

file.Properties.System.Author.Value = new string[] { "Author #1", "Author #2" };
file.Properties.System.Title.Value = "Example Title";

// Alternate way to Write:

ShellPropertyWriter propertyWriter =  file.Properties.GetPropertyWriter();
propertyWriter.WriteProperty(SystemProperties.System.Author, new string[] { "Author" });
propertyWriter.Close();**_
#########################################################################
I have the following error

_**ParserError:
Line |
   1 |  using Microsoft.WindowsAPICodePack.Shell;
     |       ~
     | Missing using directive**_

Can you help me please.

Regards,
Djeff

**Comment by anhellwig** [comment]
Your code looks like C# code to me, not like a PowerShell script.

**Comment by contre** [comment]
This isn't a tested use for the library so I won't be of much help here.

**Comment by GH-Djeff** [comment]
Thank you all for your help. I'll be back with a new code
