### ISSUE TITLE
WindowClassEx - struct layouts do not match native layouts

### ISSUE THREAD

**Issue by mediabuff** [contre/Windows-API-Code-Pack-1.1#43]
https://github.com/contre/Windows-API-Code-Pack-1.1/blob/master/source/WindowsAPICodePack/Shell/Interop/ShellObjectWatcher/ShellObjectWatcherNativeMethods.cs

Following is completely incorrect:

[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    internal struct WindowClassEx
    {
        internal IntPtr BackgroundBrushHandle;
        internal string ClassName;
        internal IntPtr CursorHandle;
        internal int ExtraClassBytes;
        internal int ExtraWindowBytes;
        internal IntPtr IconHandle;
        internal IntPtr InstanceHandle;
        internal string MenuName;
        internal uint Size;
        internal IntPtr SmallIconHandle;
        internal uint Style;
        internal ShellObjectWatcherNativeMethods.WndProcDelegate WndProc;
    }

The original repo 
https://github.com/aybe/Windows-API-Code-Pack-1.1/blob/master/source/WindowsAPICodePack/Shell/Interop/ShellObjectWatcher/ShellObjectWatcherNativeMethods.cs

[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    internal struct WindowClassEx
    {
        internal uint Size;
        internal uint Style;
        internal ShellObjectWatcherNativeMethods.WndProcDelegate WndProc;
        
        internal int ExtraClassBytes;
        internal int ExtraWindowBytes;
        internal IntPtr InstanceHandle;
        internal IntPtr IconHandle;
        internal IntPtr CursorHandle;
        internal IntPtr BackgroundBrushHandle;
        
        internal string MenuName;
        internal string ClassName;
        
        internal IntPtr SmallIconHandle;
    }

This above reflectts MS documentation
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexw

typedef struct tagWNDCLASSEXW {
      UINT      cbSize;
      UINT      style;
      WNDPROC   lpfnWndProc;
      int       cbClsExtra;
      int       cbWndExtra;
      HINSTANCE hInstance;
      HICON     hIcon;
      HCURSOR   hCursor;
      HBRUSH    hbrBackground;
      LPCWSTR   lpszMenuName;
      LPCWSTR   lpszClassName;
      HICON     hIconSm;
} WNDCLASSEXW, *PWNDCLASSEXW, *NPWNDCLASSEXW, *LPWNDCLASSEXW

**Comment by contre** [comment]
I took the changes to this file from the update provided by @dahall so he would need to comment as to why the layout was changed.

Does this result in any kind of bug or incorrect behavior? If so, can you provide a minimal repro?

**Comment by mediabuff** [comment]
Of course, RegisterClassExW pinvoke will fail - as the parameter order and the size of the structure is different.

**Comment by dahall** [comment]
@mediabuff is correct. That layout got inadvertently sorted by the code cleanup tool I use (CodePlex) and this didn't get caught in testing. My apologies. I'll push a PR to correct today. I'll also do a quick scan to see what else got sorted by field name. The cleanup is supposed to ignore all structs with StructLayoutAttribute, but if it failed once, it may have failed other times.

**Comment by dahall** [comment]
@contre It appears that all the structs without explicit `StructLayout` attributes had their fields sorted in my PR. I'm very sorry. There are many structs in the current code base whose layout will break the Win32 calls. I'm so very sorry. It is a case I hadn't considered. I would recommend rolling out all my changes and going back to the code before my submission. I'm actually surprised this is the first bug report. Please let me know how I can help.

**Comment by dahall** [comment]
I'm going through the current code to see if there is a way to determine which structures were messed up. I'll report back in a few hours. If there is a simple way to check all the structures against the originals, I'd rather just fix them than have to revert all the fixes and updates since I screwed things up.

**Comment by contre** [comment]
That would be my preference as well.

**Comment by dahall** [comment]
Turns out the munging wasn't too serious, only 5 structures. I will submit a PR shortly.

**Comment by contre** [comment]
Closed by #45
